name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm --prefix ./my-movie_server install ./my-movie_server

    - name: Run Tests
      run: npm --prefix ./my-movie_server test
